### ISSUE TITLE
Bug / Suggestion

### ISSUE THREAD

**Issue by nnourr** [ubercow/bandcamp_volume#20]
When listening to Monstercat, for example, the volume bar does not appear. This only happens to websites that are not [artistname].bandcamp.com, like for example music.monstercat.com, so if you could extend your support to these websites, by maybe having a manual switch, that force implements the volume adjuster in whatever websites you are you using, then remember the websites for automatic engagement. This means that every artist will be supported, without having to go through all the bandcamp artists and implement them yourself.

**Comment by helloitszak** [comment]
Hey @profeind,
I'm currently working on a big overhaul of the code for Bandcamp Volume, this is one of the things I'm trying to address. I'm tracking this issue over at #2 so please follow that issue.
